### **1. Indicizzazione booleana**

1. Creare un nuovo vettore con tutti i numeri primi tra 0 e 20. I numeri primi compresi tra 0 e 20 sono: **2, 3, 5, 7, 11, 13, 17, 19**.

2. Utilizza un test logico (ad esempio `>`, `<`, `==`, `!=`) per **selezionare tutte le voci del vettore maggiori di 10**.

3. Utilizza un test logico per selezionare **tutti i numeri primi pari** dalla lista.  


In [4]:

import numpy as np

# Creazione del vettore originale
primi = np.array([2, 3, 5, 7, 11, 13, 17, 19])
print("Vettore originale:", primi)

# Creazione della maschera booleana (opzionale, per capire il meccanismo)
maschera_maggiori_10 = primi > 10
print("Maschera booleana (> 10):", maschera_maggiori_10)

# Applicazione della maschera per filtrare i dati
maggiori_10 = primi[primi > 10]
print("Numeri primi > 10:", maggiori_10)


# Test logico per trovare i numeri divisibili per 2
primi_pari = primi[primi % 2 == 0]
print("Numeri primi pari:", primi_pari)




Vettore originale: [ 2  3  5  7 11 13 17 19]
Maschera booleana (> 10): [False False False False  True  True  True  True]
Numeri primi > 10: [11 13 17 19]
Numeri primi pari: [2]


### **3. Seleziona il numero più vicino a 0.5 in un array casuale**
Genera un array 10 x 3 con numeri casuali nell'intervallo [0,1].
Per ogni riga, seleziona il numero più vicino a 0.5. Per farlo usa il fancy indexing.

In [5]:
import numpy as np

# 1. Genera un array 10 x 3 con numeri casuali in [0, 1]
np.random.seed(42) 
passo1 = np.random.rand(10, 3)
print("Array Casuale Originale (10x3):\n", passo1)
print("-" * 50)

# 2. Calcola la distanza assoluta da 0.5
distanze = np.abs(passo1 - 0.5)

# 3. Trova l'indice del valore minimo lungo l'asse delle colonne (axis=1)

indici_colonne = np.argmin(distanze, axis=1)
print("Indici delle colonne con il valore più vicino a 0.5 per riga:\n", indici_colonne)
print("-" * 50)

# 4. Applicazione del Fancy Indexing
# Creiamo un array di indici di riga da 0 a 9
indici_righe = np.arange(10)

# Usiamo una coppia di array di indici (indici_righe, indici_colonne) 
# per estrarre esattamente un elemento per riga
valori_vicini = passo1[indici_righe, indici_colonne]

print("Valori finali più vicini a 0.5 per ciascuna riga:\n", valori_vicini)

Array Casuale Originale (10x3):
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643]
 [0.43194502 0.29122914 0.61185289]
 [0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378]
 [0.51423444 0.59241457 0.04645041]]
--------------------------------------------------
Indici delle colonne con il valore più vicino a 0.5 per riga:
 [0 0 2 0 1 2 0 2 0 0]
--------------------------------------------------
Valori finali più vicini a 0.5 per ciascuna riga:
 [0.37454012 0.59865848 0.60111501 0.70807258 0.21233911 0.52475643
 0.43194502 0.36636184 0.45606998 0.51423444]


### **4. Analisi della Frequenza Cardiaca con NumPy**

1. **Supponiamo che i seguenti valori rappresentino la tua frequenza cardiaca** registrata dal tuo Fitbit durante la giornata:  
   `68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70`  
   Inserisci questi valori in un array NumPy.

2. **Trova la frequenza cardiaca minima** registrata durante la giornata.  
   _(Questo valore rappresenta approssimativamente la tua frequenza cardiaca a riposo, un comune indicatore di salute.)_

3. **Trova la frequenza cardiaca massima** registrata durante la giornata.  
   _(Questo valore è un'indicazione dell'intensità dell'esercizio fisico.)_

4. **Calcoliamo la percentuale di letture effettuate mentre stavi facendo esercizio fisico (frequenza cardiaca sopra a 120)**:  
   - Crea un nuovo array che contiene `True` quando la frequenza cardiaca è **superiore a 120**, e `False` quando è **inferiore o uguale a 120**.
   - Utilizza una funzione di sintesi per calcolare la percentuale di osservazioni in cui la tua frequenza cardiaca era sopra 120.


In [2]:
import numpy as np

# Creazione dell'array con i dati del Fitbit
frequenza_cardiaca = np.array([68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70])
print("Dati della frequenza cardiaca:", frequenza_cardiaca)

# Calcolo del minimo
fc_minima = np.min(frequenza_cardiaca)
print(f"Frequenza cardiaca minima (a riposo): {fc_minima} BPM")

# Calcolo del massimo
fc_massima = np.max(frequenza_cardiaca)
print(f"Frequenza cardiaca massima (picco): {fc_massima} BPM")

# - Crea l'array booleano (maschera)
fasi_esercizio = frequenza_cardiaca > 120
print("Array booleano (test > 120):\n", fasi_esercizio)

# - Calcola la percentuale usando la media
percentuale_esercizio = np.mean(fasi_esercizio) * 100
print(f"\nPercentuale di letture in fase di esercizio: {percentuale_esercizio:.2f}%")

Dati della frequenza cardiaca: [ 68  65  77 110 160 161 162 161 160 161 162 163 164 163 162 100  90  97
  72  60  70]
Frequenza cardiaca minima (a riposo): 60 BPM
Frequenza cardiaca massima (picco): 164 BPM
Array booleano (test > 120):
 [False False False False  True  True  True  True  True  True  True  True
  True  True  True False False False False False False]

Percentuale di letture in fase di esercizio: 52.38%


### **5. Manipolazione di vettori**

1. Creare un vettore contenente i seguenti stipendi: **50.000, 105.250, 55.000, 89.000**.  
Qual è il costo totale del personale (somma di tutti gli stipendi dell'azienda)?

2. Supponiamo che il nostro malvagio CEO abbia deciso di darsi un aumento.  
Modifica il vettore degli stipendi in modo che il CEO, la persona che guadagna **105.250 dollari**, riceva un aumento del **15%**.

3. Il **115%** di **105.250 dollari** è **121.037,50 dollari**.  
Questo valore è presente nel tuo array? Se no, riesci a capire il motivo?

4. Ricrea il vettore e utilizza l'argomento **`dtype`** in modo che, quando il CEO riceve un aumento del **15%**, il suo stipendio finale sia esattamente **121.037,50 dollari**.

5. Questo aumento ha infastidito l'impiegata con lo stipendio più basso (**50.000 dollari**), che ora pretende un aumento del **20%**.  
Modifica il vettore per riflettere questo cambiamento.

6. L'aumento dato al CEO e all'impiegata ha irritato gli altri due dipendenti, quindi ora devono ricevere un aumento del **10%**.  
Modifica il vettore di conseguenza.

7. Calcola il **costo totale del personale** dopo tutti gli aumenti.  
Alla fine, quanto è costato all'azienda l'aumento di circa **16.000 dollari** del CEO?


In [3]:
import numpy as np

# Creazione dell'array degli stipendi
stipendi = np.array([50000, 105250, 55000, 89000])

costo_iniziale = np.sum(stipendi)
print(f"1. Costo totale iniziale del personale: {costo_iniziale} $")

# Proviamo ad applicare l'aumento
stipendi[1] = stipendi[1] * 1.15
print("2. Array modificato:", stipendi)
print("3. Stipendio del CEO registrato:", stipendi[1])

# 4. Ricreiamo l'array specificando il dtype float
stipendi = np.array([50000, 105250, 55000, 89000], dtype=float)

# Applichiamo nuovamente l'aumento del 15% al CEO (indice 1)
stipendi[1] = stipendi[1] * 1.15
print("4. Stipendio esatto del CEO con dtype=float:", stipendi[1], "$")

# Modifica dell'impiegata all'indice 0
stipendi[0] = stipendi[0] * 1.20
print("5. Array dopo l'aumento all'impiegata:", stipendi)

# Modifica simultanea degli indici 2 e 3 (da indice 2 fino alla fine)
stipendi[2:] = stipendi[2:] * 1.10
print("6. Array finale dopo tutti gli aumenti:", stipendi)

# Calcolo del costo totale finale
costo_finale = np.sum(stipendi)

# Calcolo di quanto è costato l'effetto domino degli aumenti all'azienda
spesa_totale_aumenti = costo_finale - costo_iniziale

print(f"7. Costo totale finale del personale: {costo_finale:.2f} $")
print(f"   L'aumento del CEO è costato all'azienda un totale di: {spesa_totale_aumenti:.2f} $")

1. Costo totale iniziale del personale: 299250 $
2. Array modificato: [ 50000 121037  55000  89000]
3. Stipendio del CEO registrato: 121037
4. Stipendio esatto del CEO con dtype=float: 121037.49999999999 $
5. Array dopo l'aumento all'impiegata: [ 60000.  121037.5  55000.   89000. ]
6. Array finale dopo tutti gli aumenti: [ 60000.  121037.5  60500.   97900. ]
7. Costo totale finale del personale: 339437.50 $
   L'aumento del CEO è costato all'azienda un totale di: 40187.50 $


### **6. Valori di Co2**

1. Carica tramite numpy il file generato e salvato a lezione sulle emissioni di CO2

2. Calcola quanti valori ci CO2 sono sopra la soglia di 18  tonnellate per anno ed il loro valore medio

3. Calcola la frazione totale di emissione sopra la soglia (somma totale sopra la soglia/somma totale)

import numpy as np



import numpy as np 

In [9]:
import numpy as np

co2 = np.loadtxt("co2.csv")
print(co2)

sopra_18 = co2[co2> 18 ]

numero= sopra_18.size

media = sopra_18.mean()

print("Numero di valori sopra soglia:", numero)
print("Media valori sopra soglia:", media)

s_s=sopra_18.sum()
s_t=co2.sum()
frazione = s_s / s_t

print("frazione emission sopra_18:", frazione)


[12. 10. 22. 30. 25. 18. 15.]
Numero di valori sopra soglia: 3
Media valori sopra soglia: 25.666666666666668
frazione emission sopra_18: 0.5833333333333334


### **7. Analisi di una matrice**
Data la matrice survey con età, reddito e anni di istruzione

survey_matrix = np.array([
    [25, 40000, 10],
    [32, 52000, 12],
    [40, 63000, 14],
    [29, 47000, 11],
    [35, 58000, 13]
])


1. Seleziona dalla matrice solo gli intervistati con **almeno 12 anni di istruzione** utilizzando un test logico.

2. In un'unica riga di codice, seleziona i **redditi** degli intervistati con **almeno 12 anni di istruzione**.

3. In un'unica riga di codice, calcola il **reddito medio** degli intervistati con **almeno 12 anni di istruzione**.


In [5]:
import numpy as np

# Definizione della matrice originale (Colonne: 0 = Età, 1 = Reddito, 2 = Anni Istruzione)
survey_matrix = np.array([
    [25, 40000, 10],
    [32, 52000, 12],
    [40, 63000, 14],
    [29, 47000, 11],
    [35, 58000, 13]
])


# 1. Selezionare solo gli intervistati con almeno 12 anni di istruzione

# Gli anni di istruzione si trovano nella colonna con indice 2 (l'ultima).
# Creiamo una maschera booleana basata sulla terza colonna e filtriamo le righe.
maschera_istruzione = survey_matrix[:, 2] >= 12
intervistati_filtrati = survey_matrix[maschera_istruzione]

print("1. Righe degli intervistati con istruzione >= 12:\n", intervistati_filtrati)
print("-" * 60)


# 2. Selezionare i REDDITI degli intervistati con almeno 12 anni di istruzione

# Il reddito si trova nella colonna con indice 1. 
# Filtriamo le righe con la maschera e isoliamo la colonna 1.
redditi_filtrati = survey_matrix[survey_matrix[:, 2] >= 12, 1]

print("2. Redditi selezionati (in un'unica riga):", redditi_filtrati)
print("-" * 60)


# 3. Calcolare il REDDITO MEDIO di questi intervistati

# Passiamo l'array estratto al punto precedente direttamente a np.mean()
reddito_medio = np.mean(survey_matrix[survey_matrix[:, 2] >= 12, 1])

print(f"3. Reddito medio (in un'unica riga): {reddito_medio:.2f} $")

1. Righe degli intervistati con istruzione >= 12:
 [[   32 52000    12]
 [   40 63000    14]
 [   35 58000    13]]
------------------------------------------------------------
2. Redditi selezionati (in un'unica riga): [52000 63000 58000]
------------------------------------------------------------
3. Reddito medio (in un'unica riga): 57666.67 $


### **8. Rimpiazzare gli outliers**

Vediamo se possiamo ripulire alcuni dati mancanti. Immagina di essere il responsabile dei registri di un comune locale con **500 cittadini** di **55 anni e oltre**.  

La città è famosa per la sua longevità e un team di ricercatori ti ha chiesto di identificare **il cittadino più anziano**.  

Il problema è che, occasionalmente, nei registri si verificano errori e in quei casi viene inserita l'età **999** invece dell'età corretta.  

Rimuovi i dati errati dall'array e determina l'età del cittadino più anziano.


In [6]:
ages = np.array([92, 108, 75, 63, 62, 66, 90, 98, 97, 92, 60, 107, 90, 71, 97, 86, 55, 55,
                 98, 57, 96, 104, 96, 94, 72, 98, 111, 98, 89, 69, 77, 92, 85, 101, 93, 100,
                 90, 101, 96, 98, 999, 87, 106, 86, 108, 55, 67, 65, 68, 59, 67, 72, 57, 79,
                 95, 67, 86, 70, 91, 111, 67, 75, 59, 88, 90, 99, 94, 65, 111, 103, 100, 70,
                 63, 65, 100, 110, 999, 70, 57, 75, 56, 104, 111, 90, 74, 100, 90, 86, 88, 99,
                 58, 103, 88, 103, 64, 96, 105, 89, 83, 65, 100, 62, 73, 105, 83, 105, 58, 96,
                 77, 74, 95, 109, 91, 101, 91, 999, 63, 111, 97, 108, 75, 77, 73, 58, 94, 83,
                 90, 61, 110, 107, 105, 85, 64, 66, 71, 107, 105, 72, 78, 66, 100, 102, 72, 999,
                 74, 68, 73, 72, 90, 93, 99, 55, 92, 83, 58, 71, 89, 75, 98, 87, 999, 78,
                 97, 71, 106, 83, 58, 81, 100, 72, 93, 70, 65, 60, 95, 107, 94, 77, 87, 90,
                 82, 56, 99, 107, 86, 56, 73, 96, 64, 69, 64, 92, 57, 104, 110, 69, 66, 68,
                 84, 89, 72, 80, 55, 75, 87, 57, 106, 69, 66, 62, 102, 76, 111, 999, 96, 83,
                 84, 61, 102, 63, 107, 63, 76, 58, 83, 58, 61, 71, 77, 90, 74, 100, 103, 74,
                 92, 102, 63, 87, 93, 61, 63, 86, 74, 98, 64, 999, 78, 95, 84, 81, 107, 85,
                 79, 82, 89, 65, 107, 57, 74, 77, 97, 92, 58, 96, 105, 60, 55, 74, 57, 80,
                 62, 85, 87, 62, 999, 71, 74, 70, 97, 59, 82, 96, 105, 70, 89, 105, 60, 70,
                 87, 999, 64, 108, 107, 104, 85, 95, 108, 74, 64, 97, 89, 88, 79, 67, 81, 92,
                 63, 80, 76, 94, 104, 67, 73, 61, 99, 96, 68, 90, 86, 79, 85, 111, 75, 98,
                 81, 111, 108, 103, 85, 72, 108, 102, 999, 64, 107, 112, 66, 93, 89, 78, 66, 92,
                 63, 101, 92, 64, 72, 56, 71, 64, 87, 78, 107, 85, 109, 95, 69, 111, 64, 72,
                 55, 66, 99, 57, 78, 55, 58, 90, 88, 71, 90, 103, 92, 98, 67, 97, 77, 68,
                 77, 59, 78, 69, 77, 81, 61, 99, 999, 85, 78, 104, 97, 95, 74, 70, 69, 83,
                 68, 68, 77, 60, 85, 82, 93, 66, 71, 62, 64, 107, 999, 65, 78, 59, 83, 67,
                 108,  58,  95, 106,  83,  79,  67,  59,  96,  90,  55,  55,  96, 109,  82,  55, 101,  58,
                 97, 77, 60, 81, 999, 81, 75, 100, 66, 65, 105, 94, 101, 56, 999, 59, 105, 59,
                 93, 56, 104, 74, 81, 62, 76, 65, 107, 60, 107, 98, 77, 86, 83, 104, 74, 69,
                 97, 80, 91, 56, 108, 87, 65, 91, 93, 60, 91, 110, 107, 88, 96, 70, 60, 99,
                 66, 91, 107, 65, 81, 109, 84, 106, 80, 92, 78, 84, 91, 59])
import numpy as np




# Inseriamo artificialmente alcuni errori "999" nei registri
indici_errori = [12, 45, 120, 342, 411]
ages[indici_errori] = 999

# 2. Identificazione e rimozione degli outlier tramite test logico (!= 999)
eta_valide = ages[ages != 999]

# 3. Determinazione del cittadino più anziano sul campione pulito
eta_massima = np.max(eta_valide)

print(f"Numero di record totali: {len(ages)}")
print(f"Numero di record validi (senza 999): {len(eta_valide)}")
print(f"L'età del cittadino più anziano è: {eta_massima} anni")

Numero di record totali: 500
Numero di record validi (senza 999): 481
L'età del cittadino più anziano è: 112 anni


### 9.**Generazione random di storie**

Usando la lista qui sotto, estrai casualmente **5 parole con reinserimento** (cioè, i duplicati sono ammessi).  

Successivamente, inserisci casualmente queste parole negli spazi vuoti (indicati con "_") nella seguente frase:

*"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico __ che proteggeva. Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il __ come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "__".  
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un __.  
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.  
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: "Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza _!" Ci fu grande gioia e celebrazione."*


In [3]:
lista_parole = [
    'INSEDIAMENTO', 'SEPARAZIONE', 'DIFFERENZA', 'APPLICAZIONE', 'ATTEGGIAMENTO', 'VERDURA', 'IMPERO', 'RICEVIMENTO',
    'IGNORANZA', 'BIOGRAFIA', 'VISIONE', 'AGENTE DI POLIZIA', 'PROVA', 'PRESTAZIONE', 'PRESENTAZIONE', 'PARENTE',
    'GIUSTIFICAZIONE', 'FILOSOFIA', 'DIREZIONE', 'BENEFICIARIO', 'BATTERIA', 'CERIMONIA', 'AGONIA', 'RECUPERO',
    'ALFABETIZZAZIONE', 'CONSEGNA', 'SERBATOIO', 'VOLONTARIO', 'DEPOSITO', 'BIRILLO DA BOWLING', 'NEMICO', 'ANNUNCIO',
    'CARAMELLA ZUCCHERATA', 'FULMINE', 'PALLONCINO', 'COPERTA', 'SCOPERTA', 'PENALITÀ', 'GENERALE', 'ALPACA',
    'VANTAGGIO', 'HOT DOG', 'ABITO', 'MATEMATICA', 'VARIANTE'
]

import numpy as np


# 2. Estrazione casuale di 5 parole CON reinserimento (replace=True)
np.random.seed(42)  # Rende l'estrazione riproducibile ad ogni esecuzione
parole_estratte = np.random.choice(lista_parole, size=5, replace=True)

print("Parole estratte casualmente:", parole_estratte)
print("-" * 60)

# 3. Costruzione della storia inserendo le parole estratte negli spazi vuoti
# Associano ogni elemento dell'array parole_estratte a uno spazio vuoto (_) in ordine
storia = f"""In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico {parole_estratte[0]} che proteggeva. 
Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il {parole_estratte[1]} come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "{parole_estratte[2]}".  
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un {parole_estratte[3]}.  
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.  
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: "Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza {parole_estratte[4]}!" Ci fu grande gioia e celebrazione."""

# 4. Stampa del risultato finale
print(storia)

Parole estratte casualmente: ['GENERALE' 'DEPOSITO' 'PRESENTAZIONE' 'ABITO' 'RICEVIMENTO']
------------------------------------------------------------
In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico GENERALE che proteggeva. 
Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il DEPOSITO come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "PRESENTAZIONE".  
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un ABITO.  
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.  
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: "Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza RICEVIMENTO!" Ci fu grande gioia e celebrazione.


Esempio di output


"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico APPLICAZIONE che proteggeva. 
Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante 
e le offrì il DEPOSITO come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "PRESTAZIONE".  

Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un BIRILLO DA BOWLING. 
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo. 
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: 
"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza GIUSTIFICAZIONE!"  

Ci fu grande gioia e celebrazione."